language: python
python:
  - 2.7
  - 3.4
  - 3.5
  - 3.6
  - 3.7
install:
  - python setup.py install
before_script:
  # Get the linting outputs, but don't fail if they're poor
  - megaqc lint || true
script: megaqc test
